export type Company = {
  id: string;
  company_name: string;
  corp_id: string | null;
  uni_credit_id: string | null;
  province: string | null;
  city: string | null;
  sector_cat_i: string | null;
  sector_cat_ii: string | null;
  sector_cat_iii: string | null;
  main_product: string | null;
  sector_attractiveness_status: string | null;
  credit_cat: string | null;
  listed_status: string | null;
  listed_code: string | null;
  pre_listed_status: string | null;
  national_zjtx_status: string | null;
  provincial_zjtx_status: string | null;
  capital_market_financing_status: string | null;
  dengling_status: string | null;
  industry_specific_competitive_tag: string | null;
  corp_scale: string | null;
  group_name: string | null;
  short_intro: string | null;
  established_year: string | null;
  staff_number: string | null;
  registered_capital_10k_rmb: string | null;
  revenue_100mn_rmb: string | null;
  revenue_growth_rate: string | null;
  net_profit_100mn_rmb: string | null;
  gpm: string | null;
  npm: string | null;
  total_asset_100mn_rmb: string | null;
  total_liability_100mn_rmb: string | null;
  asset_liability_ratio: string | null;
  marketing_strategy: string | null;
  risk_strategy: string | null;
  product_recommend: string | null;
  source_note: string | null;
  updated_at: string | null;
};

export type CompanyRow = Company;
