/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'

const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/credit': typeof CreditRoute
  '/industry': typeof IndustryRoute
  '/playbook': typeof PlaybookRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/credit': typeof CreditRoute
  '/industry': typeof IndustryRoute
  '/playbook': typeof PlaybookRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/credit': typeof CreditRoute
  '/industry': typeof IndustryRoute
  '/playbook': typeof PlaybookRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/credit'
    | '/industry'
    | '/playbook'
    | '/companies/$id'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/credit'
    | '/industry'
    | '/playbook'
    | '/companies/$id'
    | '/companies'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/credit'
    | '/industry'
    | '/playbook'
    | '/companies/$id'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CreditRoute: typeof CreditRoute
  IndustryRoute: typeof IndustryRoute
  PlaybookRoute: typeof PlaybookRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CreditRoute: CreditRoute,
  IndustryRoute: IndustryRoute,
  PlaybookRoute: PlaybookRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
