/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as RegionalStrategyRouteImport } from './routes/regional-strategy'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as PeerSuccessCasesRouteImport } from './routes/peer-success-cases'
import { Route as KeyAccountTemplatesRouteImport } from './routes/key-account-templates'
import { Route as IndustrySolutionsRouteImport } from './routes/industry-solutions'
import { Route as IndustryOverviewRouteImport } from './routes/industry-overview'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as DueDiligenceTemplatesRouteImport } from './routes/due-diligence-templates'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as DueDiligenceCasesIndexRouteImport } from './routes/due-diligence-cases.index'
import { Route as CustomerMarketingGuideIndexRouteImport } from './routes/customer-marketing-guide.index'
import { Route as CreditStandardsIndexRouteImport } from './routes/credit-standards.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as MarketingIdRouteImport } from './routes/marketing.$id'
import { Route as DueDiligenceCasesIdRouteImport } from './routes/due-diligence-cases.$id'
import { Route as CustomerMarketingGuideIdRouteImport } from './routes/customer-marketing-guide.$id'
import { Route as CreditStandardsIdRouteImport } from './routes/credit-standards.$id'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalStrategyRoute = RegionalStrategyRouteImport.update({
  id: '/regional-strategy',
  path: '/regional-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PeerSuccessCasesRoute = PeerSuccessCasesRouteImport.update({
  id: '/peer-success-cases',
  path: '/peer-success-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyAccountTemplatesRoute = KeyAccountTemplatesRouteImport.update({
  id: '/key-account-templates',
  path: '/key-account-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySolutionsRoute = IndustrySolutionsRouteImport.update({
  id: '/industry-solutions',
  path: '/industry-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryOverviewRoute = IndustryOverviewRouteImport.update({
  id: '/industry-overview',
  path: '/industry-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const DueDiligenceTemplatesRoute = DueDiligenceTemplatesRouteImport.update({
  id: '/due-diligence-templates',
  path: '/due-diligence-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const DueDiligenceCasesIndexRoute = DueDiligenceCasesIndexRouteImport.update({
  id: '/due-diligence-cases/',
  path: '/due-diligence-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMarketingGuideIndexRoute =
  CustomerMarketingGuideIndexRouteImport.update({
    id: '/customer-marketing-guide/',
    path: '/customer-marketing-guide/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreditStandardsIndexRoute = CreditStandardsIndexRouteImport.update({
  id: '/credit-standards/',
  path: '/credit-standards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIdRoute = MarketingIdRouteImport.update({
  id: '/marketing/$id',
  path: '/marketing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DueDiligenceCasesIdRoute = DueDiligenceCasesIdRouteImport.update({
  id: '/due-diligence-cases/$id',
  path: '/due-diligence-cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMarketingGuideIdRoute =
  CustomerMarketingGuideIdRouteImport.update({
    id: '/customer-marketing-guide/$id',
    path: '/customer-marketing-guide/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreditStandardsIdRoute = CreditStandardsIdRouteImport.update({
  id: '/credit-standards/$id',
  path: '/credit-standards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/credit': typeof CreditRoute
  '/due-diligence-templates': typeof DueDiligenceTemplatesRoute
  '/industry': typeof IndustryRoute
  '/industry-overview': typeof IndustryOverviewRoute
  '/industry-solutions': typeof IndustrySolutionsRoute
  '/key-account-templates': typeof KeyAccountTemplatesRoute
  '/peer-success-cases': typeof PeerSuccessCasesRoute
  '/playbook': typeof PlaybookRoute
  '/regional-strategy': typeof RegionalStrategyRoute
  '/training': typeof TrainingRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/credit-standards/$id': typeof CreditStandardsIdRoute
  '/customer-marketing-guide/$id': typeof CustomerMarketingGuideIdRoute
  '/due-diligence-cases/$id': typeof DueDiligenceCasesIdRoute
  '/marketing/$id': typeof MarketingIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/credit-standards/': typeof CreditStandardsIndexRoute
  '/customer-marketing-guide/': typeof CustomerMarketingGuideIndexRoute
  '/due-diligence-cases/': typeof DueDiligenceCasesIndexRoute
  '/marketing/': typeof MarketingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/credit': typeof CreditRoute
  '/due-diligence-templates': typeof DueDiligenceTemplatesRoute
  '/industry': typeof IndustryRoute
  '/industry-overview': typeof IndustryOverviewRoute
  '/industry-solutions': typeof IndustrySolutionsRoute
  '/key-account-templates': typeof KeyAccountTemplatesRoute
  '/peer-success-cases': typeof PeerSuccessCasesRoute
  '/playbook': typeof PlaybookRoute
  '/regional-strategy': typeof RegionalStrategyRoute
  '/training': typeof TrainingRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/credit-standards/$id': typeof CreditStandardsIdRoute
  '/customer-marketing-guide/$id': typeof CustomerMarketingGuideIdRoute
  '/due-diligence-cases/$id': typeof DueDiligenceCasesIdRoute
  '/marketing/$id': typeof MarketingIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/credit-standards': typeof CreditStandardsIndexRoute
  '/customer-marketing-guide': typeof CustomerMarketingGuideIndexRoute
  '/due-diligence-cases': typeof DueDiligenceCasesIndexRoute
  '/marketing': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/credit': typeof CreditRoute
  '/due-diligence-templates': typeof DueDiligenceTemplatesRoute
  '/industry': typeof IndustryRoute
  '/industry-overview': typeof IndustryOverviewRoute
  '/industry-solutions': typeof IndustrySolutionsRoute
  '/key-account-templates': typeof KeyAccountTemplatesRoute
  '/peer-success-cases': typeof PeerSuccessCasesRoute
  '/playbook': typeof PlaybookRoute
  '/regional-strategy': typeof RegionalStrategyRoute
  '/training': typeof TrainingRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/credit-standards/$id': typeof CreditStandardsIdRoute
  '/customer-marketing-guide/$id': typeof CustomerMarketingGuideIdRoute
  '/due-diligence-cases/$id': typeof DueDiligenceCasesIdRoute
  '/marketing/$id': typeof MarketingIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/credit-standards/': typeof CreditStandardsIndexRoute
  '/customer-marketing-guide/': typeof CustomerMarketingGuideIndexRoute
  '/due-diligence-cases/': typeof DueDiligenceCasesIndexRoute
  '/marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/credit'
    | '/due-diligence-templates'
    | '/industry'
    | '/industry-overview'
    | '/industry-solutions'
    | '/key-account-templates'
    | '/peer-success-cases'
    | '/playbook'
    | '/regional-strategy'
    | '/training'
    | '/companies/$id'
    | '/credit-standards/$id'
    | '/customer-marketing-guide/$id'
    | '/due-diligence-cases/$id'
    | '/marketing/$id'
    | '/companies/'
    | '/credit-standards/'
    | '/customer-marketing-guide/'
    | '/due-diligence-cases/'
    | '/marketing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/credit'
    | '/due-diligence-templates'
    | '/industry'
    | '/industry-overview'
    | '/industry-solutions'
    | '/key-account-templates'
    | '/peer-success-cases'
    | '/playbook'
    | '/regional-strategy'
    | '/training'
    | '/companies/$id'
    | '/credit-standards/$id'
    | '/customer-marketing-guide/$id'
    | '/due-diligence-cases/$id'
    | '/marketing/$id'
    | '/companies'
    | '/credit-standards'
    | '/customer-marketing-guide'
    | '/due-diligence-cases'
    | '/marketing'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/credit'
    | '/due-diligence-templates'
    | '/industry'
    | '/industry-overview'
    | '/industry-solutions'
    | '/key-account-templates'
    | '/peer-success-cases'
    | '/playbook'
    | '/regional-strategy'
    | '/training'
    | '/companies/$id'
    | '/credit-standards/$id'
    | '/customer-marketing-guide/$id'
    | '/due-diligence-cases/$id'
    | '/marketing/$id'
    | '/companies/'
    | '/credit-standards/'
    | '/customer-marketing-guide/'
    | '/due-diligence-cases/'
    | '/marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CreditRoute: typeof CreditRoute
  DueDiligenceTemplatesRoute: typeof DueDiligenceTemplatesRoute
  IndustryRoute: typeof IndustryRoute
  IndustryOverviewRoute: typeof IndustryOverviewRoute
  IndustrySolutionsRoute: typeof IndustrySolutionsRoute
  KeyAccountTemplatesRoute: typeof KeyAccountTemplatesRoute
  PeerSuccessCasesRoute: typeof PeerSuccessCasesRoute
  PlaybookRoute: typeof PlaybookRoute
  RegionalStrategyRoute: typeof RegionalStrategyRoute
  TrainingRoute: typeof TrainingRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  CreditStandardsIdRoute: typeof CreditStandardsIdRoute
  CustomerMarketingGuideIdRoute: typeof CustomerMarketingGuideIdRoute
  DueDiligenceCasesIdRoute: typeof DueDiligenceCasesIdRoute
  MarketingIdRoute: typeof MarketingIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  CreditStandardsIndexRoute: typeof CreditStandardsIndexRoute
  CustomerMarketingGuideIndexRoute: typeof CustomerMarketingGuideIndexRoute
  DueDiligenceCasesIndexRoute: typeof DueDiligenceCasesIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional-strategy': {
      id: '/regional-strategy'
      path: '/regional-strategy'
      fullPath: '/regional-strategy'
      preLoaderRoute: typeof RegionalStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peer-success-cases': {
      id: '/peer-success-cases'
      path: '/peer-success-cases'
      fullPath: '/peer-success-cases'
      preLoaderRoute: typeof PeerSuccessCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-account-templates': {
      id: '/key-account-templates'
      path: '/key-account-templates'
      fullPath: '/key-account-templates'
      preLoaderRoute: typeof KeyAccountTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-solutions': {
      id: '/industry-solutions'
      path: '/industry-solutions'
      fullPath: '/industry-solutions'
      preLoaderRoute: typeof IndustrySolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-overview': {
      id: '/industry-overview'
      path: '/industry-overview'
      fullPath: '/industry-overview'
      preLoaderRoute: typeof IndustryOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/due-diligence-templates': {
      id: '/due-diligence-templates'
      path: '/due-diligence-templates'
      fullPath: '/due-diligence-templates'
      preLoaderRoute: typeof DueDiligenceTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/due-diligence-cases/': {
      id: '/due-diligence-cases/'
      path: '/due-diligence-cases'
      fullPath: '/due-diligence-cases/'
      preLoaderRoute: typeof DueDiligenceCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-marketing-guide/': {
      id: '/customer-marketing-guide/'
      path: '/customer-marketing-guide'
      fullPath: '/customer-marketing-guide/'
      preLoaderRoute: typeof CustomerMarketingGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-standards/': {
      id: '/credit-standards/'
      path: '/credit-standards'
      fullPath: '/credit-standards/'
      preLoaderRoute: typeof CreditStandardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/$id': {
      id: '/marketing/$id'
      path: '/marketing/$id'
      fullPath: '/marketing/$id'
      preLoaderRoute: typeof MarketingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/due-diligence-cases/$id': {
      id: '/due-diligence-cases/$id'
      path: '/due-diligence-cases/$id'
      fullPath: '/due-diligence-cases/$id'
      preLoaderRoute: typeof DueDiligenceCasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-marketing-guide/$id': {
      id: '/customer-marketing-guide/$id'
      path: '/customer-marketing-guide/$id'
      fullPath: '/customer-marketing-guide/$id'
      preLoaderRoute: typeof CustomerMarketingGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-standards/$id': {
      id: '/credit-standards/$id'
      path: '/credit-standards/$id'
      fullPath: '/credit-standards/$id'
      preLoaderRoute: typeof CreditStandardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CreditRoute: CreditRoute,
  DueDiligenceTemplatesRoute: DueDiligenceTemplatesRoute,
  IndustryRoute: IndustryRoute,
  IndustryOverviewRoute: IndustryOverviewRoute,
  IndustrySolutionsRoute: IndustrySolutionsRoute,
  KeyAccountTemplatesRoute: KeyAccountTemplatesRoute,
  PeerSuccessCasesRoute: PeerSuccessCasesRoute,
  PlaybookRoute: PlaybookRoute,
  RegionalStrategyRoute: RegionalStrategyRoute,
  TrainingRoute: TrainingRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  CreditStandardsIdRoute: CreditStandardsIdRoute,
  CustomerMarketingGuideIdRoute: CustomerMarketingGuideIdRoute,
  DueDiligenceCasesIdRoute: DueDiligenceCasesIdRoute,
  MarketingIdRoute: MarketingIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  CreditStandardsIndexRoute: CreditStandardsIndexRoute,
  CustomerMarketingGuideIndexRoute: CustomerMarketingGuideIndexRoute,
  DueDiligenceCasesIndexRoute: DueDiligenceCasesIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
